# Default Configuration for CR24Plugins v1.0.1 by CR24 STUDIO ---> ClearRelic24
boss: 1
admin: 1
modo: 1
guide: 1
helper: 1
fondateur: 1
owner: 1
operateur: 1
vip: 1
youtuber: 1
developpeur: 1
architecte: 1
builder: 1